env:
  clientid: ${clientId}
  clientsecret: ${clientSecret}
  username: ${username}
  password: ${password}

reddit:
  accestoken:
    url: https://www.reddit.com/api/v1/access_token

app:
  useragent: JRockit 0.1